### ISSUE TITLE
3.11.0 UE 4.20.3 plugin fails cooking

### ISSUE THREAD

**Issue by younesouhbi** [getbraincloud/braincloud-unreal#57]
Windows 7
UE 4.20.3
BCClient 3.11.0

Errors:
1. BCClient\Source\BCClientPlugin\Private\BrainCloudClient.cpp(25,33) :  error: initializing wide char array with incompatible wide string literal
2. BCClient\Source\BCClientPlugin\Private\ServerCall.cpp(15,13) :  error: out-of-line definition of 'ServerCall' does not match any declaration in 'ServerCall'
3. BCClient\Source\BCClientPlugin\Private\ServerCall.cpp(21,11) :  error: no viable overloaded '='

Warnings:
1. BCClient\Source\BCClientPlugin\Private\BlueprintProxies\BCWrapperProxy.cpp(53,30) :  warning: 'getInstance' is deprecated: Use of the *singleton* has been deprecated...
2. BCClient\Source\BCClientPlugin\Private\BrainCloudRTTComms.cpp(316,25) :  warning: equality comparison with extraneous parentheses [-Wparentheses-equality]

EDIT: updated the title to lift confusion. The solution builds fine in Visual Studio but cooking fails in the editor.

**Comment by ruth0048** [comment]
This was sorted out a while ago, closing issue
